### ISSUE TITLE
Episode on cernopendata-client?

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshopwhepp-lesson-dataset-scouting#1]
@jmhogan Would you like me to add an episode of [cernopendata-client](https://cernopendata-client.readthedocs.io/en/latest/) here or would it make the lesson too long?

As they all have docker at this point, it could be

```
docker pull docker.io/cernopendata/cernopendata-client
docker run -i -t --rm docker.io/cernopendata/cernopendata-client --help
```

and then an example command on how to get e.g. the file listings:

```
docker run -i -t --rm docker.io/cernopendata/cernopendata-client  get-file-locations --recid 24103 --protocol xrootd
```

If the schedule is too tight, we could then think of adding it for the next workshop.

**Comment by jmhogan** [comment]
@katilp that's a great idea. The docker instruction should work, especially if this image is small and doesn't take long to pull. 

Maybe you could add an episode after the existing 03, and move the existing 04/05 to become 05/06?

**Comment by katilp** [comment]
Perfect, I'll do that. The image is  631MB so it should be OK.
